// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MonoSiri",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "モノシリ",
            targets: ["AppModule"],
            bundleIdentifier: "io.github.ys7i.monosiri",
            teamIdentifier: "",
            displayVersion: "0.1.0",
            bundleVersion: "1",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .locationWhenInUse(purposeString: "今いる場所にまつわるWikipediaの記事を探すために使います。")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
